In [22]:
import numpy as np

# Q3:Creating a 4×5 array of all True's
array = np.full((4, 5), True, dtype=bool)
array

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [24]:
# Q4: Create an array of integers from 10 to 50 with with step of 3. Save the array in a. Replace all even numbers in a with -1.
a = np.arange(10, 51, 3)
a[a % 2 == 0] = -1
a

array([-1, 13, -1, 19, -1, 25, -1, 31, -1, 37, -1, 43, -1, 49])

In [26]:
# Q5: Create an one-dimensional array which includes odd numbers from 1 to 20.
odd_numbers = np.arange(1, 21, 2)
odd_numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
# a: Change all numbers divisible by 3 into 0.
odd_numbers[odd_numbers % 3 == 0] = 0
odd_numbers

array([ 1,  0,  5,  7,  0, 11, 13,  0, 17, 19])

In [32]:
# b: Change the array into a 2x5 matrix.
matrix = odd_numbers.reshape(2, 5)
matrix

array([[ 1,  0,  5,  7,  0],
       [11, 13,  0, 17, 19]])

In [34]:
# c: Convert all numbers of the third column into zero. Q6:
matrix[:, 2] = 0
matrix

array([[ 1,  0,  0,  7,  0],
       [11, 13,  0, 17, 19]])

In [36]:
# a: Create an one-dimensional array, b1, which includes 9 numbers evenly spaced over 1.5 to 3.
b1 = np.linspace(1.5, 3, 9)
b1

array([1.5   , 1.6875, 1.875 , 2.0625, 2.25  , 2.4375, 2.625 , 2.8125,
       3.    ])

In [38]:
# b: Create a 3x3 matrix, b2, which includes random numbers from Gaussian distribution with mean = 1, and sd = 0.75, seed = 1234.
np.random.seed(1234)
mean = 1
std_dev = 0.75
b2 = np.random.normal(loc=mean, scale=std_dev, size=(3, 3))
b2

array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

In [40]:
# c: Calculate the determinant of b2.
det_b2 = np.linalg.det(b2)
det_b2

-1.0770051050177027

In [42]:
# d: What is the transpose of matrix b2?
transpose_b2 = b2.T
transpose_b2

array([[1.35357637, 0.76551108, 1.64469131],
       [0.10676823, 0.45955845, 0.52260737],
       [2.07453023, 1.66537221, 1.01177228]])

In [44]:
# e: Convert b1 into a 3x3 matrix.
b1_reshaped = b1.reshape(3, 3)
b1_reshaped

array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

In [46]:
# f: Calculate summation of b1 and b2.
summation_b1_b2 = b1_reshaped + b2
summation_b1_b2

array([[2.85357637, 1.79426823, 3.94953023],
       [2.82801108, 2.70955845, 4.10287221],
       [4.26969131, 3.33510737, 4.01177228]])

In [48]:
# g: Calculate matrix multiplication of b1 and b2.
matrix_multiplication = np.dot(b1_reshaped, b2)
matrix_multiplication

array([[ 6.40596071,  1.91554605,  7.81918396],
       [ 8.52308626,  2.52807145, 10.49200098],
       [10.64021182,  3.14059686, 13.16481801]])

In [50]:
# h: Call all numbers of b2 which are greater than mean of b2.
mean_b2 = np.mean(b2)
greater_than_mean = b2[b2 > mean_b2]
greater_than_mean

array([1.35357637, 2.07453023, 1.66537221, 1.64469131])

In [ ]:
# i: Scale matrix b2 using min-max scaling method. End of Code
min_b2 = np.min(b2)
max_b2 = np.max(b2)
scaled_b2 = (b2 - min_b2) / (max_b2 - min_b2)
scaled_b2